[theme]
primaryColor="#ff4b4b"
backgroundColor="#f8f9fa"
secondaryBackgroundColor="#ffffff"
textColor="#31333f"
font="sans serif"

[server]
address = "0.0.0.0"
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = false
